import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import MainVisual from '../components/mainVisual'
import Section1 from '../components/section1'
import Section2 from '../components/section2'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainVisual />
      <Section1 />
      <Section2 />
      <Box h="100vh"></Box>
    </>
  )
}
